---
title: "ADNIMERGE2-Package-Building"
output: 
   rmarkdown::html_vignette:
     toc: false
     code_folding: hide
date: "Last Updated: `r format(Sys.Date(), '%B %d, %Y')`"
vignette: >
  %\VignetteIndexEntry{ADNIMERGE2-Package-Building}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
```

# Introduction

The document describes the procedure to build an R data package from source `.csv` files with similar workflow. 

# Building an R Package from csv files

To build an R data package from source `.csv` files with similar workflow: 

* Clone the [https://github.com/atri-biostats/ADNIMERGE2](https://github.com/atri-biostats/ADNIMERGE2) repository. This will create the following directories:
   
   + [`data-raw`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data-raw): to store raw-data
   + [`R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/R): to store package-specific defined function that includes utils function
   + [`vignettes`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/vignettes): to store guidance documents/articles about the package if necessary
   + [`tests`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/tests): to store package related test and retest scripts
   + [`tools`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/tools): to store auxiliary files that needed during package configuration
   
   Or create R package project locally and add a package metadata into the local project directory: 
 
  * The package working directory can be created using [usethis::create_package](https://usethis.r-lib.org/reference/create_package.html) function. 
  
  * The package metadata file such as `DESCRIPTION` similar to [this](https://github.com/atri-biostats/ADNIMERGE2/blob/main/DESCRIPTION) can be created using [usethis::use_description](https://usethis.r-lib.org/reference/use_description.html) function.
  
  * Copy all pre-defined scripts/functions as necessary from the [ADNIMERGE2 github repository](https://github.com/atri-biostats/ADNIMERGE2) with the same file path to the local package directory.

* Download the ADNI study data from the data-shared platform at [https://adni.loni.usc.edu/data-samples/adni-data/](https://adni.loni.usc.edu/data-samples/adni-data/) either in `*.zip` or `*.csv` file format, and store the files in [`./data-raw`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data-raw) directory
   
   + Required to download a data dictionary `*.csv` file
   
   + It is recommend to download files from the data-shared platform on the same date and without adding any file name prefix.

* Run `source('tools/build.R')` to prepare dataset, generate documentations and build R package. More details about the main procedures in [`build.R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main//tools/build.R) script are presented as follows: 

  + Data preparation: 
    
    - [`./data-raw/data_prep.R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data-raw/data_prep.R): 
         
         + To store all dataset in *`./data`* directory using [`usethis::use_data()`](https://usethis.r-lib.org/reference/use_data.html)
         
         + Some additional data preparation, please see  [here](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data-raw/data_prep.R) for more information. 
         
         + Required the data downloaded date (`DATA_DOWNLOADED_DATE`) and a Boolean value to update existing data dictionary file (`UPDATE_DATADIC`) as input arguments
         
    - [`./data-raw/data_prep_recode.R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data-raw/data_prep_recode.R): 
         
         + To decode dataset values based on a data dictionary as necessary
         
         + Required a boolean input argument regarding whether to use an UPDATED data dictionary (`USE_UPDATED_DATADIC`)
         
    - [`./tools/generate_derived_data.R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/tools/generate_derived_data.R):  
         + To generate derived dataset
         
         + Required list of derived dataset name (`DERIVED_DATASET_LIST`) as an input argument 
         
         + The derived dataset will be created based on the `.Rmd` files in the  [`vignettes`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/vignettes) directory.
      
  + Generate data-related documentations:
    
    - To create roxygen2 document for the available data in the [`./data`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/data) directory. 
    
    - [`./tools/document.R`](https://github.com/atri-biostats/ADNIMERGE2/tree/main/tools/document.R):
        
        + Using actual dataset values, and data dictionary 
        
        + Required two input arguments: a boolean indicator whether to use the `UPDATED` data dictionary (`USE_UPDATED_DATADIC`) and list of derived dataset name (`DERIVED_DATASET_LIST`)
          
  + Build the data package: using [devtools R package](https://devtools.r-lib.org/)
